import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import 'swiper/css';

import Header from "@/components/Header";

const archivo = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nicestream",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={archivo.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
